language: 
        - c

compiler:
        - gcc
        - clang

script: 
        - make 
        - make tests

notification:
        email:
                on_success: change
                on_failure: always
